# Site settings
title: Adventures in Coding
header-img: img/home-bg.png
email: julian.johannesen@gmail.com
copyright_name: julianjohannesen
description: My journey into web development
baseurl: ""
url: https://www.julianjohannesen.com
twitter_username: jjeadon
github_username:  julianjohannesen
learn_profile: julianjohannesen
email_username: julian.johannesen@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
# exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", 'vendor']
exclude: ["node_modules", 'vendor']

gems: [jekyll-paginate, jekyll-feed]

plugins:
  - jekyll-sitemap

